version: "3.9"

services:

  backend:
    container_name: casa-backend
    build:
      context: ./casa-azul-backend
    ports:
      - "8080:8080"
    networks:
      - casa-net
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: always

  frontend:
    container_name: casa-frontend
    build:
      context: ./casa-azul-frontend
    ports:
      - "4200:4000"   # Externo 4200 â†’ interno 4000 (SSR)
    depends_on:
      - backend
    networks:
      - casa-net
    restart: always

networks:
  casa-net:
    driver: bridge
